name: Deploy Agent to Vertex AI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout Code
        uses: actions/checkout@v3

      - name: 🔐 Authenticate to Google Cloud (with beta)
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: "530.0.0"
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
          install_components: beta

      - name: 🔍 Verify gcloud installation and beta component
        run: |
          gcloud --version
          gcloud components list --filter="id:beta" --format="value(state.name)"

      - name: ✅ Validate Agent Spec
        run: |
          test -f agent/hello_agent.yaml || (echo "Spec not found" && exit 1)

      - name: 📦 Ensure beta component is installed
        run: |
          echo "y" | gcloud components install beta --quiet || echo "Beta installation completed"

      - name: 🧠 Deploy Agent to Vertex AI
        run: |
          gcloud beta agent builder agents update \
            --agent=hello-agent \
            --agent-spec=agent/hello_agent.yaml \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=global \
            --quiet