name: Deploy Agent to Vertex AI

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout Code
        uses: actions/checkout@v3

      - name: 🔐 Set up Google Cloud SDK with beta
        run: |
          # Download and install gcloud SDK
          curl https://sdk.cloud.google.com | bash
          source $HOME/google-cloud-sdk/path.bash.inc
          
          # Create service account key file
          echo '${{ secrets.GCP_SA_KEY }}' | base64 -d > ${HOME}/gcp-key.json
          
          # Authenticate
          gcloud auth activate-service-account --key-file=${HOME}/gcp-key.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          
          # Install beta component non-interactively
          gcloud config set core/disable_usage_reporting true
          gcloud config set component_manager/disable_update_check true
          yes | gcloud components install beta --quiet || echo "Beta already installed or not required"
          
          # Add gcloud to PATH for subsequent steps
          echo "$HOME/google-cloud-sdk/bin" >> $GITHUB_PATH

      - name: ✅ Validate Agent Spec
        run: |
          test -f agent/hello_agent.yaml || (echo "Spec not found" && exit 1)

      - name: 🧠 Deploy Agent to Vertex AI
        run: |
          gcloud beta agent builder agents update \
            --agent=hello-agent \
            --agent-spec=agent/hello_agent.yaml \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --location=global \
            --quiet