name: Deploy Agent to Vertex AI

on:
  push:
    branches:
      - main
    paths:
      - '**.yaml'
      - '**.py'

jobs:
  deploy-agent:
    runs-on: ubuntu-latest
    env:
      GOOGLE_PROJECT: geni-project
      REGION: asia-south1

    steps:
      - name: ⏬ Checkout Code
        uses: actions/checkout@v3

      - name: 🔐 Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 🛠 Install yq
        run: |
          sudo snap install yq

      - name: 📤 Convert YAML to JSON
        run: |
          yq -o=json '.' agent/hello_agent.yaml > agent/hello_agent.json

      - name: 🚀 Deploy Agent to Vertex AI
        run: |
          curl -X POST \
            -H "Authorization: Bearer $(gcloud auth print-access-token)" \
            -H "Content-Type: application/json" \
            -d @agent/hello_agent.json \
            "https://$REGION-aiplatform.googleapis.com/v1/projects/$GOOGLE_PROJECT/locations/$REGION/agents"